### ISSUE TITLE
Planned research activities 

### ISSUE THREAD

**Issue by MartinBenediktBusch** [lexicongovernance/gov-research#1]
This epic outlines the possible research activities at `lexicon`. The following list is not exhaustive and might change. 

- [ ] Evaluate if and how collusion resistant quadratic voting is implemented in the plural-discourse prototype: https://zuzalu.network/. That is, check that the implementation follows the model described here and (if not) document differences and their implications:  https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4311507
- [ ] Create a numerical simulation of the model to further verify that the calculation in the prototype works as expected. Furthermore, such a simulation framework could be used to illustrate the impact of different parameters `lexicon` would like to implement in the future. 
- [ ] The proof of collusion resistance in https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4311507 uses the model of quadratic finance (QF) as a baseline. However, in section 1.4. they show how their results can be applied to QV. We could use this as a baseline to proof collusion resistance of QV explicitly. We could use the re-written model of collusion resistance for outreach and as a baseline for possible extensions that we might want to include. 
- [ ] Collusion resistant QV is possible due to a strategy called `Connection-Oriented Cluster Match`. The proof relies on the fact that the attenuation of the interaction term (e.g. if two users have the same affiliation is relatively coarse). That is, every contribution is either square rooted (e.g. if two users have the same affiliation) or not. One could imagine a more finely grained attenuation than this. However, whether a more fine grained attenuation is collusion-resistant or not must be proven.  
- [ ] Develop a preference model that describes which variables should and should not be taken into account for collusion resistant QV as well as their impact.
